### ISSUE TITLE
求数据集

### ISSUE THREAD

**Issue by CR7WO** [BigHeartC/Al_challenger_2018_sentiment_analysis#4]
可以给我提供一下数据集吗，网上找不到了，ruankaidong@126.com,谢谢

**Comment by philharmonic77** [comment]
抱歉打扰，我很想自己试一试，但也找了挺久找不到。如果方便的话，也请给我发一份。多谢，我的邮箱是phil77@126.com

**Comment by moneyDboat** [comment]
https://github.com/nju161250102/AI_challenger 这儿有

**Comment by liuhuihuii** [comment]
谢谢 moneyDboat
